import React, { useState } from 'react';
import { Outfit } from '../types';
import { ChevronLeft, ChevronRight, X, Share2 } from 'lucide-react';

interface CalendarViewProps {
  scheduledOutfits: Outfit[];
  onRemoveSchedule: (outfitId: string) => void;
}

const CalendarView: React.FC<CalendarViewProps> = ({ scheduledOutfits, onRemoveSchedule }) => {
  const [currentDate, setCurrentDate] = useState(new Date());
  const [selectedDay, setSelectedDay] = useState<string | null>(null);

  const getDaysInMonth = (date: Date) => {
    return new Date(date.getFullYear(), date.getMonth() + 1, 0).getDate();
  };

  const getFirstDayOfMonth = (date: Date) => {
    return new Date(date.getFullYear(), date.getMonth(), 1).getDay();
  };

  const daysInMonth = getDaysInMonth(currentDate);
  const firstDay = getFirstDayOfMonth(currentDate);

  const prevMonth = () => {
    setCurrentDate(new Date(currentDate.getFullYear(), currentDate.getMonth() - 1, 1));
    setSelectedDay(null);
  };

  const nextMonth = () => {
    setCurrentDate(new Date(currentDate.getFullYear(), currentDate.getMonth() + 1, 1));
    setSelectedDay(null);
  };

  const formatDateKey = (day: number) => {
    return `${currentDate.getFullYear()}-${String(currentDate.getMonth() + 1).padStart(2, '0')}-${String(day).padStart(2, '0')}`;
  };

  const getOutfitsForDate = (dateKey: string) => {
    return scheduledOutfits.filter(o => o.scheduledDate === dateKey);
  };

  const handleShare = async (outfit: Outfit) => {
    const text = `🔥 DripFrame Fit Check: ${outfit.name}\n\n📅 Scheduled for: ${outfit.scheduledDate}\n🧥 Items: ${outfit.items.map(i => i.category).join(', ')}\n💡 Vibe: ${outfit.reasoning}\n\nGenerated by DripFrame`;

    if (navigator.share) {
      try {
        await navigator.share({
          title: `DripFrame: ${outfit.name}`,
          text: text,
        });
      } catch (error) {
        console.log('Error sharing:', error);
      }
    } else {
      try {
        await navigator.clipboard.writeText(text);
        alert('Outfit details copied to clipboard!');
      } catch (err) {
        alert('Failed to copy to clipboard');
      }
    }
  };

  const monthNames = ["JANUARY", "FEBRUARY", "MARCH", "APRIL", "MAY", "JUNE", "JULY", "AUGUST", "SEPTEMBER", "OCTOBER", "NOVEMBER", "DECEMBER"];

  return (
    <div className="space-y-6">
      {/* Calendar Header */}
      <div className="bg-white border border-black p-4 flex items-center justify-between shadow-[4px_4px_0px_0px_rgba(0,0,0,1)]">
         <button onClick={prevMonth} className="p-2 hover:bg-gray-100 border border-transparent hover:border-black transition-all">
           <ChevronLeft className="w-6 h-6" />
         </button>
         <h2 className="text-2xl font-black uppercase italic tracking-tighter">
           {monthNames[currentDate.getMonth()]} {currentDate.getFullYear()}
         </h2>
         <button onClick={nextMonth} className="p-2 hover:bg-gray-100 border border-transparent hover:border-black transition-all">
           <ChevronRight className="w-6 h-6" />
         </button>
      </div>

      <div className="flex flex-col md:flex-row gap-6">
        {/* Calendar Grid */}
        <div className="flex-1 bg-white border border-black p-4 shadow-[4px_4px_0px_0px_rgba(0,0,0,1)]">
           <div className="grid grid-cols-7 gap-1 mb-2">
             {['S','M','T','W','T','F','S'].map((d, i) => (
               <div key={i} className="text-center font-black text-xs text-gray-400 py-2">{d}</div>
             ))}
           </div>
           
           <div className="grid grid-cols-7 gap-1">
             {Array.from({ length: firstDay }).map((_, i) => (
               <div key={`empty-${i}`} className="aspect-square bg-gray-50/50" />
             ))}
             {Array.from({ length: daysInMonth }).map((_, i) => {
               const day = i + 1;
               const dateKey = formatDateKey(day);
               const outfits = getOutfitsForDate(dateKey);
               const isToday = new Date().toDateString() === new Date(currentDate.getFullYear(), currentDate.getMonth(), day).toDateString();
               const isSelected = selectedDay === dateKey;

               return (
                 <button 
                   key={day}
                   onClick={() => setSelectedDay(dateKey)}
                   className={`aspect-square border relative transition-all group ${
                     isSelected 
                       ? 'bg-black text-[#CCFF00] border-black scale-105 z-10 shadow-[2px_2px_0px_0px_#CCFF00]' 
                       : 'bg-white text-black border-gray-200 hover:border-black hover:z-10'
                   }`}
                 >
                   <span className={`absolute top-1 left-1 text-xs font-bold ${isToday ? 'underline decoration-[#CCFF00] decoration-2' : ''}`}>
                     {day}
                   </span>
                   
                   {outfits.length > 0 && (
                     <div className="absolute inset-0 flex items-center justify-center pt-3 pointer-events-none">
                        <div className="w-full h-full p-2 flex items-end justify-end">
                           <div className="bg-[#CCFF00] text-black text-[10px] font-black px-1 border border-black">
                             {outfits.length}
                           </div>
                        </div>
                     </div>
                   )}
                 </button>
               );
             })}
           </div>
        </div>

        {/* Selected Day Details */}
        <div className="w-full md:w-80 space-y-4">
          <div className="bg-black text-white p-4 border border-black shadow-[4px_4px_0px_0px_#CCFF00]">
            <h3 className="font-black uppercase text-lg">
              {selectedDay ? new Date(selectedDay).toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric' }) : 'Select a Date'}
            </h3>
          </div>

          {selectedDay ? (
             <div className="space-y-4">
               {getOutfitsForDate(selectedDay).length === 0 ? (
                 <div className="p-8 text-center border-2 border-dashed border-gray-300 bg-gray-50">
                   <p className="text-gray-500 font-bold text-sm uppercase">No drip scheduled</p>
                 </div>
               ) : (
                 getOutfitsForDate(selectedDay).map(outfit => (
                   <div key={outfit.id} className="bg-white border border-black p-3 relative group animate-in slide-in-from-right-4">
                      {/* Actions Container - Visible on mobile, hover on desktop */}
                      <div className="absolute top-2 right-2 flex gap-2 opacity-100 sm:opacity-0 sm:group-hover:opacity-100 transition-all bg-white pl-2 z-10">
                        <button 
                          onClick={() => handleShare(outfit)}
                          className="text-gray-400 hover:text-black hover:scale-110 transition-all"
                          title="Share"
                        >
                          <Share2 className="w-4 h-4" />
                        </button>
                        <button 
                          onClick={() => onRemoveSchedule(outfit.id)}
                          className="text-gray-400 hover:text-red-500 hover:scale-110 transition-all"
                          title="Unschedule"
                        >
                          <X className="w-4 h-4" />
                        </button>
                      </div>

                      <p className="font-black uppercase text-sm mb-1 pr-16 truncate">{outfit.name}</p>
                      <span className="text-xs font-bold bg-[#CCFF00] px-1 border border-black inline-block mb-3">{outfit.occasion}</span>
                      
                      <div className="flex flex-col gap-2">
                        <div className="flex -space-x-2 overflow-hidden">
                            {outfit.items.slice(0, 4).map(item => (
                            <div key={item.id} className="w-8 h-8 rounded-full border border-black bg-white overflow-hidden">
                                <img src={item.imageUrl} alt="" className="w-full h-full object-cover" />
                            </div>
                            ))}
                            {outfit.items.length > 4 && (
                                <div className="w-8 h-8 rounded-full border border-black bg-gray-100 flex items-center justify-center text-[10px] font-bold z-10">
                                    +{outfit.items.length - 4}
                                </div>
                            )}
                        </div>
                        <p className="text-xs text-gray-500 font-medium line-clamp-2">
                            <span className="font-bold text-black uppercase">Includes:</span> {outfit.items.map(i => i.category).join(', ')}
                        </p>
                      </div>
                   </div>
                 ))
               )}
             </div>
          ) : (
            <div className="p-4 text-sm text-gray-500 font-medium italic">
              Tap a day on the calendar to see your scheduled fits.
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default CalendarView;
