import React, { useState, useMemo } from 'react';
import { Outfit } from '../types';
import { Heart, Trash2, Sparkles, Star, Lightbulb, CheckCircle2, History, Clock, ChevronDown, ChevronUp, Share2, CalendarPlus, X, ArrowUpDown } from 'lucide-react';

interface SavedOutfitsProps {
  savedOutfits: Outfit[];
  historyOutfits: Outfit[];
  onToggleFavorite: (outfit: Outfit) => void;
  onDelete: (id: string) => void;
  onSchedule: (outfit: Outfit, date: string) => void;
}

const SavedOutfits: React.FC<SavedOutfitsProps> = ({ savedOutfits, historyOutfits, onToggleFavorite, onDelete, onSchedule }) => {
  const [activeTab, setActiveTab] = useState<'favorites' | 'history'>('favorites');
  const [expandedOutfitId, setExpandedOutfitId] = useState<string | null>(null);
  const [historySort, setHistorySort] = useState<'newest' | 'oldest'>('newest');

  // Scheduling State
  const [schedulingOutfitId, setSchedulingOutfitId] = useState<string | null>(null);
  const [scheduleDate, setScheduleDate] = useState<string>("");

  const displayedOutfits = useMemo(() => {
    if (activeTab === 'favorites') return savedOutfits;
    
    // History Logic
    // Default order (newest) is how it comes from props.
    if (historySort === 'newest') return historyOutfits;
    
    // Sort oldest first (reverse the array)
    return [...historyOutfits].reverse();
  }, [activeTab, savedOutfits, historyOutfits, historySort]);

  const toggleExpand = (id: string) => {
    setExpandedOutfitId(prev => prev === id ? null : id);
  };

  const handleShare = async (e: React.MouseEvent, outfit: Outfit) => {
    e.stopPropagation();
    const text = `🔥 DripFrame Fit Check: ${outfit.name}\n\n📅 Occasion: ${outfit.occasion}\n🧥 Items: ${outfit.items.map(i => i.category).join(', ')}\n💡 Vibe: ${outfit.reasoning}\n\nGenerated by DripFrame`;

    if (navigator.share) {
      try {
        await navigator.share({
          title: `DripFrame: ${outfit.name}`,
          text: text,
        });
      } catch (error) {
        console.log('Error sharing:', error);
      }
    } else {
      try {
        await navigator.clipboard.writeText(text);
        alert('Outfit details copied to clipboard!');
      } catch (err) {
        alert('Failed to copy to clipboard');
      }
    }
  };

  const openScheduleModal = (e: React.MouseEvent, outfit: Outfit) => {
    e.stopPropagation();
    setSchedulingOutfitId(outfit.id);
    setScheduleDate(new Date().toISOString().split('T')[0]);
  };

  const confirmSchedule = () => {
    if (!schedulingOutfitId || !scheduleDate) return;
    const outfit = displayedOutfits.find(o => o.id === schedulingOutfitId);
    if (outfit) {
      onSchedule(outfit, scheduleDate);
      setSchedulingOutfitId(null);
      alert("Outfit scheduled successfully!");
    }
  };

  return (
    <div className="space-y-6">
       {/* Header - Stacked on mobile to prevent overlap */}
       <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
         <div className="flex items-center gap-4">
            <h2 className="text-2xl font-black uppercase italic text-black">
              {activeTab === 'favorites' ? 'My Favorites' : 'Generation History'}
            </h2>
            
            {activeTab === 'history' && historyOutfits.length > 0 && (
               <div className="relative">
                 <select 
                   value={historySort}
                   onChange={(e) => setHistorySort(e.target.value as 'newest' | 'oldest')}
                   className="appearance-none bg-white border border-black px-3 py-1 pr-8 text-xs font-bold uppercase focus:outline-none shadow-[2px_2px_0px_0px_rgba(0,0,0,1)] cursor-pointer hover:bg-gray-50 transition-colors"
                 >
                   <option value="newest">Newest First</option>
                   <option value="oldest">Oldest First</option>
                 </select>
                 <ArrowUpDown className="w-3 h-3 absolute right-2 top-1/2 -translate-y-1/2 pointer-events-none text-gray-500" />
               </div>
            )}
         </div>
         
         <div className="flex bg-white border border-black p-1 shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] self-start sm:self-auto">
           <button
             onClick={() => setActiveTab('favorites')}
             className={`px-4 py-2 text-sm font-bold uppercase transition-all flex items-center gap-2 ${
               activeTab === 'favorites' 
                 ? 'bg-black text-[#CCFF00]' 
                 : 'text-gray-500 hover:text-black'
             }`}
           >
             <Heart className="w-4 h-4" />
             Favorites
           </button>
           <button
             onClick={() => setActiveTab('history')}
             className={`px-4 py-2 text-sm font-bold uppercase transition-all flex items-center gap-2 ${
               activeTab === 'history' 
                 ? 'bg-black text-[#CCFF00]' 
                 : 'text-gray-500 hover:text-black'
             }`}
           >
             <History className="w-4 h-4" />
             History
           </button>
         </div>
       </div>

       {displayedOutfits.length === 0 ? (
         <div className="flex flex-col items-center justify-center h-[50vh] text-center animate-in fade-in duration-500">
            <div className={`p-6 rounded-full mb-4 border-2 border-black ${activeTab === 'favorites' ? 'bg-[#CCFF00]' : 'bg-gray-100'}`}>
              {activeTab === 'favorites' ? (
                <Heart className="w-10 h-10 text-black fill-current" />
              ) : (
                <Clock className="w-10 h-10 text-black" />
              )}
            </div>
            <h2 className="text-xl font-black uppercase text-black">
              {activeTab === 'favorites' ? 'No favorites yet' : 'No history yet'}
            </h2>
            <p className="text-gray-500 mt-2 max-w-xs mx-auto font-medium">
              {activeTab === 'favorites' 
                ? 'Save outfits from the generator to build your personal lookbook.' 
                : 'Generated outfits will appear here automatically.'}
            </p>
         </div>
       ) : (
         <div className="grid gap-6" style={{ contentVisibility: 'auto' }}>
          {displayedOutfits.map((outfit) => {
            const isSaved = savedOutfits.some(o => o.id === outfit.id);
            const isExpanded = expandedOutfitId === outfit.id;
            const hasAiContent = outfit.rating || outfit.generatedImageUrl;

            return (
              <div 
                key={outfit.id} 
                // Card is now clickable if it has AI content to show
                onClick={hasAiContent ? () => toggleExpand(outfit.id) : undefined}
                className={`bg-white border border-black shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] overflow-hidden animate-in slide-in-from-bottom-2 duration-500 transition-all ${hasAiContent ? 'cursor-pointer hover:bg-gray-50' : ''}`}
              >
                <div className="p-4 border-b border-black bg-gray-50 flex justify-between items-center">
                   <div className="flex flex-col items-start gap-2">
                      <h3 className="font-bold text-black uppercase text-lg leading-tight">{outfit.name}</h3>
                      <span className="text-xs font-bold text-black bg-[#CCFF00] border border-black px-2 py-0.5">{outfit.occasion}</span>
                   </div>
                   
                   <div className="flex items-center gap-2" onClick={(e) => e.stopPropagation()}>
                      <button 
                          onClick={(e) => handleShare(e, outfit)}
                          className="p-2 text-black hover:text-[#CCFF00] hover:scale-110 transition-all"
                          title="Share"
                      >
                          <Share2 className="w-5 h-5" />
                      </button>

                      <button
                        onClick={(e) => openScheduleModal(e, outfit)}
                        className="p-2 text-black hover:text-[#CCFF00] hover:scale-110 transition-all"
                        title="Schedule"
                      >
                         <CalendarPlus className="w-5 h-5" />
                      </button>

                      {activeTab === 'history' && (
                         <button 
                           onClick={() => onToggleFavorite(outfit)}
                           className={`p-2 border border-black transition-colors ${
                             isSaved 
                               ? 'bg-black text-[#CCFF00]' 
                               : 'bg-white text-gray-400 hover:bg-[#CCFF00] hover:text-black'
                           }`}
                           title={isSaved ? "Remove from favorites" : "Save to favorites"}
                         >
                           <Heart className={`w-5 h-5 ${isSaved ? 'fill-current' : ''}`} />
                         </button>
                      )}
                      
                      {activeTab === 'favorites' && (
                        <button 
                          onClick={() => onDelete(outfit.id)}
                          className="text-black border border-transparent hover:border-black hover:bg-black hover:text-white transition-all p-2"
                          title="Remove from favorites"
                        >
                          <Trash2 className="w-5 h-5" />
                        </button>
                      )}
                   </div>
                </div>
                
                <div className="p-4">
                   {/* Items Grid */}
                   <div className="flex -space-x-4 overflow-hidden py-2 px-2 mb-3">
                     {outfit.items.map((item, i) => (
                       <div key={item.id} className="w-16 h-16 rounded-full border-2 border-black bg-white overflow-hidden relative z-[10]" style={{ zIndex: 10 - i}}>
                         <img src={item.imageUrl} alt="" className="w-full h-full object-cover" />
                       </div>
                     ))}
                   </div>
                   <p className="text-sm font-medium text-black line-clamp-2 italic mb-2">"{outfit.reasoning}"</p>
                  
                   {hasAiContent && (
                     <>
                        <div className="flex justify-center mt-2 mb-2">
                           {isExpanded ? <ChevronUp className="w-5 h-5 text-gray-400" /> : <ChevronDown className="w-5 h-5 text-gray-400" />}
                        </div>

                       {isExpanded && (
                         <div className="animate-in slide-in-from-top-2 fade-in duration-300 space-y-4 pt-2 border-t border-dashed border-gray-300">
                            {/* Generated Visual Display */}
                           {outfit.generatedImageUrl && (
                             <div className="border border-black p-2 bg-gray-50">
                               <div className="flex items-center gap-1.5 mb-2">
                                 <Sparkles className="w-3 h-3 text-black" />
                                 <span className="text-xs font-black text-black uppercase">AI Lookbook</span>
                               </div>
                               <div className="h-64 w-full border border-black overflow-hidden bg-white">
                                  <img src={outfit.generatedImageUrl} alt="Lookbook" className="w-full h-full object-cover object-top" />
                               </div>
                             </div>
                           )}

                           {/* Rating Display */}
                           {outfit.rating && (
                             <div className="bg-gray-100 p-3 border border-black">
                                <div className="flex items-center gap-2 mb-2">
                                    <div className="flex items-center gap-1 bg-black text-[#CCFF00] px-2 py-0.5 text-xs font-bold border border-black">
                                      <Star className="w-3 h-3 fill-current" />
                                      <span>{outfit.rating}/10</span>
                                    </div>
                                    <span className="text-xs text-black font-bold uppercase">Stylist Rating</span>
                                </div>
                                <p className="text-sm text-black mb-3 italic">"{outfit.critique}"</p>
                                {outfit.stylingTips && outfit.stylingTips.length > 0 && (
                                  <div className="space-y-1">
                                     {outfit.stylingTips.map((tip, idx) => (
                                       <div key={idx} className="flex items-start gap-1.5 text-xs text-black font-medium">
                                         <CheckCircle2 className="w-3 h-3 text-[#CCFF00] fill-black shrink-0 mt-0.5" />
                                         <span>{tip}</span>
                                       </div>
                                     ))}
                                  </div>
                                )}
                             </div>
                           )}
                         </div>
                       )}
                     </>
                   )}
                </div>
              </div>
            );
          })}
         </div>
       )}

      {/* Schedule Modal */}
      {schedulingOutfitId && (
        <div className="fixed inset-0 z-50 bg-black/80 flex items-center justify-center p-4">
          <div className="bg-white border-2 border-black p-6 w-full max-w-sm shadow-[8px_8px_0px_0px_#CCFF00] animate-in zoom-in-95 duration-200">
            <div className="flex justify-between items-center mb-6">
              <h3 className="font-black uppercase text-xl italic tracking-tight">Schedule Drip</h3>
              <button onClick={() => setSchedulingOutfitId(null)} className="hover:rotate-90 transition-transform"><X className="w-6 h-6" /></button>
            </div>
            
            <label className="block text-xs font-black uppercase mb-2 tracking-wide">Select Date</label>
            <div className="relative mb-8">
              <input 
                type="date" 
                value={scheduleDate}
                onChange={(e) => setScheduleDate(e.target.value)}
                className="w-full bg-white border-2 border-black p-4 font-black uppercase text-lg text-black shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] focus:outline-none focus:shadow-none focus:translate-x-[2px] focus:translate-y-[2px] transition-all cursor-pointer"
                style={{ colorScheme: 'light' }}
              />
            </div>

            <button 
              onClick={confirmSchedule}
              className="w-full bg-black text-[#CCFF00] font-black uppercase py-4 text-lg hover:bg-[#CCFF00] hover:text-black border-2 border-transparent hover:border-black transition-all shadow-[4px_4px_0px_0px_rgba(0,0,0,0)] hover:shadow-[4px_4px_0px_0px_rgba(0,0,0,1)]"
            >
              Confirm Schedule
            </button>
          </div>
        </div>
      )}
    </div>
  );
};

export default SavedOutfits;
